### ISSUE TITLE
生成支付二维码异常

### ISSUE THREAD

**Issue by 10hz-404** [essensoft/paylinks#153]
之前刚开始用的时候好像还没出现过这种情况，这两天和前端对接时出现了

**==============   生成微信二维码的异常 ========================**
异常信息：System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The response ended prematurely.
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Essensoft.AspNetCore.Payment.WeChatPay.V3.Extensions.HttpClientExtensions.PostAsync[T](HttpClient client, IWeChatPayPostRequest`1 request, WeChatPayOptions options)
   at Essensoft.AspNetCore.Payment.WeChatPay.V3.WeChatPayClient.ExecuteAsync[T](IWeChatPayPostRequest`1 request, WeChatPayOptions options)
   at Agiso.DigiShop.Core.Pay.Manager.WeChatPayManager.GeneratePayCode(GeneratePayCodeInput data) in C:\AgisoGits\AgisoProjects\DigiShop\Agiso.DigiShop.Core\Pay\Manager\WeChatPayManager.cs:line 102

ProgramName:WebDigiShopBuyer@172.26.81.16,e:System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at System.Net.HttpWebRequest.GetResponse()
   at Agiso.Utils.Util.DoPost(String url, Dictionary`2 postParameters, Nullable`1 timeout, Nullable`1 readWriteTimeout, Dictionary`2 reqHeaders, String httpProxyAddr)
   at Agiso.Utils.Util.DoExecuteWithOpenApi(String url, Dictionary`2 param, String secret, HttpMethod method, Int32 timeout, Int32 readWriteTimeout)
   at Agiso.Utils.LogReporter.ReportLog(LogItem log)
   
**==============   生成支付宝二维码的异常 ========================**
异常信息：System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: NotTimeValid
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Essensoft.AspNetCore.Payment.Alipay.Extensions.HttpClientExtensions.PostAsync(HttpClient client, String url, IDictionary`2 textParams)
   at Essensoft.AspNetCore.Payment.Alipay.AlipayClient.ExecuteAsync[T](IAlipayRequest`1 request, AlipayOptions options, String accessToken, String appAuthToken, String targetAppId)
   at Essensoft.AspNetCore.Payment.Alipay.AlipayClient.ExecuteAsync[T](IAlipayRequest`1 request, AlipayOptions options, String accessToken, String appAuthToken)
   at Essensoft.AspNetCore.Payment.Alipay.AlipayClient.ExecuteAsync[T](IAlipayRequest`1 request, AlipayOptions options, String accessToken)
   at Essensoft.AspNetCore.Payment.Alipay.AlipayClient.ExecuteAsync[T](IAlipayRequest`1 request, AlipayOptions options)
   at Agiso.DigiShop.Core.Pay.Manager.AliPayManager.GeneratePayCode(GeneratePayCodeInput data) in C:\AgisoGits\AgisoProjects\DigiShop\Agiso.DigiShop.Core\Pay\Manager\AliPayManager.cs:line 110

ProgramName:WebDigiShopBuyer@172.26.81.16,e:System.Net.WebException: The remote server returned an error: (401) Unauthorized.
   at System.Net.HttpWebRequest.GetResponse()
   at Agiso.Utils.Util.DoPost(String url, Dictionary`2 postParameters, Nullable`1 timeout, Nullable`1 readWriteTimeout, Dictionary`2 reqHeaders, String httpProxyAddr)
   at Agiso.Utils.Util.DoExecuteWithOpenApi(String url, Dictionary`2 param, String secret, HttpMethod method, Int32 timeout, Int32 readWriteTimeout)
   at Agiso.Utils.LogReporter.ReportLog(LogItem log)
   
==========   **运行环境**===========
dotnet版本：.net5
"Essensoft.AspNetCore.Payment.Alipay" Version="3.3.2"
"Essensoft.AspNetCore.Payment.WeChatPay" Version="3.3.2"
使用VisualStudio的IIS方式启动
尝试过把IIS的SSl选项勾选启动
无论http（本地）还是https（本地）都不行，这个异常是概率发生的，而且第一次生成时发生的概率最大，然后后续生成几乎没问题

我试过在网上找解决方案，也就是在项目启动时添加以下代码，但是这种方法不安全
```c#
// 禁用证书名称检查和证书吊销列表检查
ServicePointManager.ServerCertificateValidationCallback += (sender, certificate, chain, sslPolicyErrors) => true;
```

作者可以帮忙解惑一下吗，不知道是什么问题。

**Comment by roc916** [comment]
是否有可能是网络问题，例如说代理造成的？

**Comment by 10hz-404** [comment]
> 是否有可能是网络问题，例如说代理造成的？

我在本地运行时后台是开启了规则代理，但是前端对接时请求的是在测试服务器的程序，测试服务器应该是没有开启代理的，两个环境都出现了这个问题，所以不太确定，我周一在本地关闭代理调试一下。

**Comment by 10hz-404** [comment]
> 是否有可能是网络问题，例如说代理造成的？

我刚才尝试了关闭代理的情况下，这种异常还是会存在。

**Comment by 10hz-404** [comment]
补充一下，支付宝使用的是沙箱环境的网关，不知道是否和这个有关

**Comment by 10hz-404** [comment]
![1686977135598](https://github.com/essensoft/paylink/assets/80660002/ddc18ae1-0759-44c0-8d95-c10388c342ee)

**Comment by roc916** [comment]
刚刚我使用项目实例，无法复现这个问题。

运行环境:
Win11
VS 17.6
IIS Express
.NET 5
Payment 3.3.2

<img width="973" alt="image" src="https://github.com/essensoft/paylink/assets/12685126/43932147-bbc3-4b32-8745-7d5a6e1ce704">

**Comment by 10hz-404** [comment]
> 刚刚我使用项目实例，无法复现这个问题。
> 
> 运行环境: Win11 VS 17.6 IIS Express .NET 5 Payment 3.3.2
> 
> <img alt="image" width="973" src="https://user-images.githubusercontent.com/12685126/246587095-43932147-bbc3-4b32-8745-7d5a6e1ce704.png">

这个问题可能和Payment SDK的关系不大，因为我刚开发完成支付模块时是没有任何问题的，不知道是不是后续开发其他模块的代码产生了什么冲突或者是我这边的运行环境有点问题，目前检查了一遍还看不出来，我先关闭Issues，后续如果问题能解决了我再回复下。

**Comment by 10hz-404** [comment]
问题已经解决，原因是因为支付宝沙箱环境的证书没有换到最新的，导致会请求失败。
目前直接切换到正式环境开发了。
![71e3f5131a98e7a0827e047d0a8c510a](https://github.com/essensoft/paylink/assets/80660002/d755964b-0b0b-41f7-8d29-5c146739dce8)
