### ISSUE TITLE
电脑网站支付异常

### ISSUE THREAD

**Issue by Alvin-4550** [essensoft/paylinks#156]
Dear：
各位开发同仁，首先非常感谢你们开源了PayLink的这个项目，非常感谢。我在初次接触中遇到了以下问题：
首先1：支付宝已经绑定了电脑支付的产品
2.关于支付宝公钥私钥密钥上传也已经设置。
目前测试了2中情况：
1.使用的测试页面是电脑网站支付：
    第一种测试，使用密钥测试：配置文件配置了AppId，AlipayPublicKey，AppPrivateKey，ServerUrl，SignType，证书相关参数设置为“”（空）。
    第二种测试，使用公钥测试：1.配置了AppId , AppPrivateKey , ServerUrl , SignType ,AppPublicCert ,AlipayPublicCert  AlipayRootCert

"AppPublicCert": "D:\\Project\\AiPint\\AiHintServer\\alipay\\appCertPublicKey.crt",
"AlipayPublicCert": "D:\\Project\\AiPint\\AiHintServer\\alipay\\alipayCertPublicKey_RSA2.crt",
"AlipayRootCert": "D:\\Project\\AiPint\\AiHintServer\\alipay\\alipayRootCert.crt"

以上2种方式都测试了，但是都出现了以下的报错。

An unhandled exception occurred while processing the request.
AsnContentException: The provided data is tagged with 'Universal' class value '16', but it should have been 'Universal' class value '2'.
System.Formats.Asn1.AsnDecoder.CheckExpectedTag(Asn1Tag tag, Asn1Tag expectedTag, UniversalTagNumber tagNumber)

CryptographicException: ASN1 corrupted data.
System.Security.Cryptography.Asn1.RSAPrivateKeyAsn.Decode(Asn1Tag expectedTag, ReadOnlyMemory<byte> encoded, AsnEncodingRules ruleSet)

AsnContentException: The provided data is tagged with 'Universal' class value '16', but it should have been 'Universal' class value '2'.
System.Formats.Asn1.AsnDecoder.CheckExpectedTag(Asn1Tag tag, Asn1Tag expectedTag, UniversalTagNumber tagNumber)
System.Formats.Asn1.AsnDecoder.GetPrimitiveContentSpan(ReadOnlySpan<byte> source, AsnEncodingRules ruleSet, Asn1Tag expectedTag, UniversalTagNumber tagNumber, out int bytesConsumed)
System.Formats.Asn1.AsnDecoder.GetIntegerContents(ReadOnlySpan<byte> source, AsnEncodingRules ruleSet, Asn1Tag expectedTag, UniversalTagNumber tagNumber, out int bytesConsumed)
System.Formats.Asn1.AsnDecoder.ReadIntegerBytes(ReadOnlySpan<byte> source, AsnEncodingRules ruleSet, out int bytesConsumed, Nullable<Asn1Tag> expectedTag)
System.Formats.Asn1.AsnDecoder.ReadInteger(ReadOnlySpan<byte> source, AsnEncodingRules ruleSet, out int bytesConsumed, Nullable<Asn1Tag> expectedTag)
System.Security.Cryptography.Asn1.RSAPrivateKeyAsn.DecodeCore(ref AsnValueReader reader, Asn1Tag expectedTag, ReadOnlyMemory<byte> rebind, out RSAPrivateKeyAsn decoded)
System.Security.Cryptography.Asn1.RSAPrivateKeyAsn.Decode(Asn1Tag expectedTag, ReadOnlyMemory<byte> encoded, AsnEncodingRules ruleSet)

Show raw exception details
System.Formats.Asn1.AsnContentException: The provided data is tagged with 'Universal' class value '16', but it should have been 'Universal' class value '2'.
   at System.Formats.Asn1.AsnDecoder.CheckExpectedTag(Asn1Tag tag, Asn1Tag expectedTag, UniversalTagNumber tagNumber)
   at System.Formats.Asn1.AsnDecoder.GetPrimitiveContentSpan(ReadOnlySpan`1 source, AsnEncodingRules ruleSet, Asn1Tag expectedTag, UniversalTagNumber tagNumber, Int32& bytesConsumed)
   at System.Formats.Asn1.AsnDecoder.GetIntegerContents(ReadOnlySpan`1 source, AsnEncodingRules ruleSet, Asn1Tag expectedTag, UniversalTagNumber tagNumber, Int32& bytesConsumed)
   at System.Formats.Asn1.AsnDecoder.ReadIntegerBytes(ReadOnlySpan`1 source, AsnEncodingRules ruleSet, Int32& bytesConsumed, Nullable`1 expectedTag)
   at System.Formats.Asn1.AsnDecoder.ReadInteger(ReadOnlySpan`1 source, AsnEncodingRules ruleSet, Int32& bytesConsumed, Nullable`1 expectedTag)
   at System.Security.Cryptography.Asn1.RSAPrivateKeyAsn.DecodeCore(AsnValueReader& reader, Asn1Tag expectedTag, ReadOnlyMemory`1 rebind, RSAPrivateKeyAsn& decoded)
   at System.Security.Cryptography.Asn1.RSAPrivateKeyAsn.Decode(Asn1Tag expectedTag, ReadOnlyMemory`1 encoded, AsnEncodingRules ruleSet)

CryptographicException: ASN1 corrupted data.
System.Security.Cryptography.Asn1.RSAPrivateKeyAsn.Decode(Asn1Tag expectedTag, ReadOnlyMemory<byte> encoded, AsnEncodingRules ruleSet)
System.Security.Cryptography.RSAKeyFormatHelper.FromPkcs1PrivateKey(ReadOnlyMemory<byte> keyData, ref AlgorithmIdentifierAsn algId, out RSAParameters ret)
System.Security.Cryptography.RSA.ImportRSAPrivateKey(ReadOnlySpan<byte> source, out int bytesRead)
Essensoft.Paylink.Security.SHA256WithRSA.Sign(string data, string privateKey) in SHA256WithRSA.cs
+
                rsa.ImportRSAPrivateKey(Convert.FromBase64String(privateKey), out var _);
Essensoft.Paylink.Alipay.Utility.AlipaySignature.RSASignContent(string data, string privateKey, string signType) in AlipaySignature.cs
+
                "RSA2" => SHA256WithRSA.Sign(data, privateKey),
Essensoft.Paylink.Alipay.AlipayClient.PageExecuteAsync<T>(IAlipayRequest<T> request, AlipayOptions options, string accessToken, string appAuthToken, string reqMethod) in AlipayClient.cs
+
            txtParams.Add(AlipayConstants.SIGN, AlipaySignature.RSASignContent(signContent, options.AppPrivateKey, options.SignType));
Essensoft.Paylink.Alipay.AlipayClient.PageExecuteAsync<T>(IAlipayRequest<T> request, AlipayOptions options, string accessToken, string reqMethod) in AlipayClient.cs
+
            return await PageExecuteAsync(request, options, accessToken, null, reqMethod);
Essensoft.Paylink.Alipay.AlipayClient.PageExecuteAsync<T>(IAlipayRequest<T> request, AlipayOptions options) in AlipayClient.cs
+
            return await PageExecuteAsync(request, options, null, "POST");
WebApplicationSample.Controllers.AlipayController.PagePay(AlipayTradePagePayViewModel viewModel) in AlipayController.cs
+
            var response = await _client.PageExecuteAsync(req, _optionsAccessor.Value);
Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, object controller, object[] arguments)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask<IActionResult> actionResultValueTask)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

Show raw exception details
System.Security.Cryptography.CryptographicException: ASN1 corrupted data.
 ---> System.Formats.Asn1.AsnContentException: The provided data is tagged with 'Universal' class value '16', but it should have been 'Universal' class value '2'.
   at System.Formats.Asn1.AsnDecoder.CheckExpectedTag(Asn1Tag tag, Asn1Tag expectedTag, UniversalTagNumber tagNumber)
   at System.Formats.Asn1.AsnDecoder.GetPrimitiveContentSpan(ReadOnlySpan`1 source, AsnEncodingRules ruleSet, Asn1Tag expectedTag, UniversalTagNumber tagNumber, Int32& bytesConsumed)
   at System.Formats.Asn1.AsnDecoder.GetIntegerContents(ReadOnlySpan`1 source, AsnEncodingRules ruleSet, Asn1Tag expectedTag, UniversalTagNumber tagNumber, Int32& bytesConsumed)
   at System.Formats.Asn1.AsnDecoder.ReadIntegerBytes(ReadOnlySpan`1 source, AsnEncodingRules ruleSet, Int32& bytesConsumed, Nullable`1 expectedTag)
   at System.Formats.Asn1.AsnDecoder.ReadInteger(ReadOnlySpan`1 source, AsnEncodingRules ruleSet, Int32& bytesConsumed, Nullable`1 expectedTag)
   at System.Security.Cryptography.Asn1.RSAPrivateKeyAsn.DecodeCore(AsnValueReader& reader, Asn1Tag expectedTag, ReadOnlyMemory`1 rebind, RSAPrivateKeyAsn& decoded)
   at System.Security.Cryptography.Asn1.RSAPrivateKeyAsn.Decode(Asn1Tag expectedTag, ReadOnlyMemory`1 encoded, AsnEncodingRules ruleSet)
   --- End of inner exception stack trace ---
   at System.Security.Cryptography.Asn1.RSAPrivateKeyAsn.Decode(Asn1Tag expectedTag, ReadOnlyMemory`1 encoded, AsnEncodingRules ruleSet)
   at System.Security.Cryptography.RSAKeyFormatHelper.FromPkcs1PrivateKey(ReadOnlyMemory`1 keyData, AlgorithmIdentifierAsn& algId, RSAParameters& ret)
   at System.Security.Cryptography.RSA.ImportRSAPrivateKey(ReadOnlySpan`1 source, Int32& bytesRead)
   at Essensoft.Paylink.Security.SHA256WithRSA.Sign(String data, String privateKey) in D:\Project\net7\paylink\src\Essensoft.Paylink.Security\SHA256WithRSA.cs:line 23
   at Essensoft.Paylink.Alipay.Utility.AlipaySignature.RSASignContent(String data, String privateKey, String signType) in D:\Project\net7\paylink\src\Essensoft.Paylink.Alipay\Utility\AlipaySignature.cs:line 37
   at Essensoft.Paylink.Alipay.AlipayClient.PageExecuteAsync[T](IAlipayRequest`1 request, AlipayOptions options, String accessToken, String appAuthToken, String reqMethod) in D:\Project\net7\paylink\src\Essensoft.Paylink.Alipay\AlipayClient.cs:line 99
   at Essensoft.Paylink.Alipay.AlipayClient.PageExecuteAsync[T](IAlipayRequest`1 request, AlipayOptions options, String accessToken, String reqMethod) in D:\Project\net7\paylink\src\Essensoft.Paylink.Alipay\AlipayClient.cs:line 37
   at Essensoft.Paylink.Alipay.AlipayClient.PageExecuteAsync[T](IAlipayRequest`1 request, AlipayOptions options) in D:\Project\net7\paylink\src\Essensoft.Paylink.Alipay\AlipayClient.cs:line 32
   at WebApplicationSample.Controllers.AlipayController.PagePay(AlipayTradePagePayViewModel viewModel) in D:\Project\net7\paylink\samples\WebApplicationSample\Controllers\AlipayController.cs:line 167
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

**Comment by roc916** [comment]
AppPrivateKey 私钥默认生成的为PCKS8(JAVA)， 请尝试转为 PKCS1

**Comment by Alvin-4550** [comment]
@roc916  非常感谢！看到你的回复后，按照提示在工具中转为PKCS1格式，报错消失，网页跳转到了支付宝页面，但是页面提示：
“调试错误，请回到请求来源地，重新发起请求。
错误代码 app-cert-not-exist 错误原因: 应用公钥证书不存在
说明:如果您不是因为本接口集成调试而看见该错误提醒，请联系本次请求来源网站，本错误属于网站集成接口的错误。”
文件路径这样配置是错误的吗："AppPublicCert": "D:\\Project\\AiPint\\AiHintServer\\alipay\\appCertPublicKey.crt",，我的证书没有放到网站的目录，只是磁盘的一个绝对路径。

**Comment by roc916** [comment]
建议重新生成并配置，怀疑与支付宝后台配置的信息不一致造成的。

**Comment by Alvin-4550** [comment]
@roc916  还没睡！要早点休息。
我是重新上传了证书到支付宝平台的然后才测试的。要不我明天在重新上传一次看看。不管证书放在哪里，现在配置的路径的写法是对的吧？"AppPublicCert": "D:\Project\AiPint\AiHintServer\alipay\appCertPublicKey.crt",。
另外想问下钉钉的群号搜不到，想问下还可以加群嚒？

**Comment by Alvin-4550** [comment]
@roc916 已经找到问题的原因： 支付宝平台更新了证书后需要让证书立即启用。立即启用证书后页面报错不再是证书相关的报错。非常感谢！
